name: 'Codeowners Lint'
description: 'Lints CODEOWNERS files'
inputs:
  dir:
    description: 'Directory to run'
    required: false
    default: '.'
  token:
    description: 'Github token to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.token }}
